sqlite: &sqlite
  adapter: sqlite3 
  database: db/<%= Rails.env %>.sqlite3 
  
mysql: &mysql 
  adapter: mysql2 
  username: root 
  password: 
  database: blogit_app_<%= Rails.env %>
  
postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password: 
  database: blogit_app_<%= Rails.env %>
  min_messages: ERROR 
  
defaults: &defaults
  pool: 5 
  timeout: 5000 
  host: localhost 
  # Use sqlite by default
  <<: *<%= ENV['DB'] || "sqlite" %>
  
development: 
  <<: *defaults 
  
test:
  <<: *defaults